module.exports = {
  queryString: [
    'css',
    'linux',
    'android',
    'html',
    'frontend',
    'google',
    'gadgets',
    'technology',
    'geek',
    'lifehack',
    'behance',
    'github',
    'muzli',
    'superhero',
    'html5',
    'javascript',
    'css3',
    'bootstrap',
    'samsung',
    'apple',
    'windows',
    'open source'
    
  ],
  queryStringSubQuery: [
    ' handy tip',
    ' tricks',
    ' tools',
    ' top',
    ' code',
    ' devices'
    
  ],
  blockedStrings: [
    'porn',
    '@POTUS',
    'sex',
    'hot',
    'girls',
    'makeup',
    'fashion',
    'naked',
    'coupon',
    'free',
    'sexy',
    'ladies',
    'cosplay',
    'spanking',
    'referral',
    'ass',
    'shit',
    'order',
    'promo',
    'tickets',
    'politics',
    'president',
    'trump',
    'sign',
    'mums',
    'mothers',
    'moms',
    'music',
    'allah',
    'arabic',
    'arabia',
    'muslim'
  ],
  resultType: [
    'mixed',
    'recent',
    'popular'
  ],
  responseString: [
    'Hi @screenName thanks for the follow! !',
    '@screenName thanks for following! !',
    'Hey @screenName thanks for the follow! !',
    'Thanks for following @screenName! !',
    'Hey @screenName, thanks for following! !',
    'Awesome @screenName, thanks for following! !',
    'Thanks for the follow @screenName! !',
    'Thanks for following @screenName! How are you today? !'
  ]
}
